version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "tk.airshipcraft:commonlib"
    ignore:
      - dependency-name: "*"
        versions: ["*"]
